import { NextResponse } from "next/server"

const data = [
    {
        title: "Esboço de conselhos ao estudante de filosofia",
        content: "O presente texto destina-se àqueles que desejam estudar filosofia e foi escrito como espécie de síntese de experiências entre o ensino e o aprendizado da matéria, por isso podendo conter explicações de tom autobiográfico seguidas de pequenas anedotas úteis à reflexão, algo que não poderia faltar em escritos que pretendam tratar do amor à sabedoria. Os conselhos e explicações aqui postos destinam-se a guiar o interessado em filosofia através da forma como ela realmente se apresenta, a saber, como problema. Por conta disso, alguns temas, perguntas e reflexões soarão estranhos e até invertidos em relação ao que normalmente se prega.",
        imgUrl: "https://miro.medium.com/v2/resize:fit:828/format:webp/1*WrObOvh3BKq0EMB08IUiBA.jpeg",
        date: "26 de janeiro de 2023"
    },
    {
        title: "Explicação e Realismo",
        content: "Um dos modos de argumentar a favor de uma teoria é mostrar que fornece uma boa explicação de um corpo de fenômenos e que ela a faz, de fato, melhor do que quaisquer alternativas disponíveis. Esse padrão de argumentação não é limitado pelo tempo ou pelo tema. Podemos encontrar tais argumentações na sociologia, na psicologia, na química e na astronomia desde os tempos de Copérnico até os mais recentes periódicos científicos.",
        imgUrl: "https://miro.medium.com/v2/resize:fit:828/format:webp/1*zM2ukv9W1fqHFNOtVFYudw.jpeg",
        date: "26 de janeiro de 2023"
    },
    {
        title: "Niilismo, Ética e o Dilema do Bonde",
        content: `O Problema do Bonde é um potencial corruptor moral pertencente a uma propaganda pró-assassinato com tendências niilistas. Ele imagina um cenário onde um bonde descontrolado pode ser desviado com o puxar duma alavanca a fim de salvar cinco vidas. Infelizmente, isso envolve o assassinato de uma pessoa inocente que, de modo contrário, o bonde não machucaria. Assassinato é definido como matar uma pessoa inocente com o intento de matar; não meramente por causa de negligência ou seja lá o que for. “Inocente” aqui significa, primeiramente, que a outra pessoa não está deliberadamente tentando matar alguém ou a ti próprio. Deixar alguém morrer não é assassinato. Quando o cenário é descrito, talvez a maioria das pessoas imagine que o moralmente correto seria puxar a alavanca e assassinar a pessoa inocente, — que por alguma razão esquecem de que a proibição do assassinato é a mais básica, fundamental e importante regra de toda a moralidade.
        O coup de grâce [golpe de misericórdia] desse convite moralmente repugnante — para assassinar e expiar — ocorre quando o cenário é reescrito de forma que, em vez de puxar a alavanca, o assassino tem de empurrar um indivíduo duma ponte, prendendo-o debaixo das rodas do bonde e prevenindo que as cinco pessoas morram dessa forma. Nessa situação, a maioria das pessoas responde que elas não irão assassinar a pessoa inocente. O professor de filosofia a ensinar a turma então aponta que ambos os cenários são lógica e moralmente idênticos. Os estudantes percebem que têm intuições morais exatamente opostas a respeito dos dois casos, encorajando-os a encarar suas intuições morais com ceticismo ou desconfiança, visto que claramente não são confiáveis em relação aos dois cenários. Não se pode confiar em intuições morais que se contradizem.[1]
        
        Conforme escrevi algures, outro cenário moralmente idêntico seria o de um homem desvairado sentado numa jangada com cinco reféns. Ele berra para ti que irá matá-los, a não ser que afogues a próxima pessoa inocente que eventualmente caminhe pela margem do lago. Tu segurá-la-ás pelo pescoço até o seu pulmão encher de água enquanto ela debate-se até a morte. Apenas um imbecil moral, o nome original para psicopatas, imaginaria que assassinar a pessoa inocente é a coisa correta por fazer. Em uma conversação recente, alguém (X) argumentou que chamar o puxar da alavanca de assassinato é falácia de petitio principii. Não o é. O puxar da alavanca condiz com a definição de assassinato — a morte ilícita e premeditada de outro ser humano inocente. O X então rescreveu o assassinato a alegando que o assassino não pretendia matar a pessoa; tencionava salvar as outras cinco. De algum jeito, ele imagina que a “real” intenção é salvar as pessoas e, afinal de contas, está apenas a puxar uma alavanca, não matando alguém.[2] O fato de que puxar a alavanca resulta na morte de alguém é irrelevante e tampouco tem algo que ver com ele. Ele não tenciona matar a pessoa inocente; ele tenciona salvar as cinco pessoas. Essa ideia insensata ignora o fato de que intentas salvar cinco pessoas com o assassinato dum inocente. O X transforma a moralidade num jogo semântico sem sentido e fala com má-fé.
        
        Palavras tais como “prevaricação”, “dissimulação”, “equívoco” e “circunlóquio” vêm à mente. Ele junta-se a Bill Clinton no grupo dos que “não fazem sexo com aquela mulher” quando perguntado por seus assessores a respeito do que Monica Lewinsky Clinton disse: “Não tem nada entre nós” numa explanação do por que ele não está mentindo ao grande júri quando disse: “Isso depende de qual o significado da palavra ‘é’ é. Se o — se ele — se ‘é’ significa é e nunca foi, isso não é — isso é uma coisa. Se isso significa que ‘nunca houve’, o depoimento era completamente verdadeiro. … Agora, se alguém tivesse me perguntado naquele dia, ‘tens tido algum tipo de relação sexual com a Sra. Lewinsky?’, isso é, feito-me uma pergunta no tempo presente, eu teria dito que não. E isso seria completamente verdade.”[3] Clinton está a mentir por omissão. De acordo com a sua pedante distinção de é/era, a não ser que ele estivesse mesmo transando com a Lewinsky enquanto era perguntado se estava a fazer sexo com ela, poderia, de consciência limpa, declarar que não. Clinton chegou ao ponto de dizer que sexo oral não é sexo; supostamente fazendo com que toda uma geração de americanos pensasse que fazer sexo oral não contaria como traição. Estou tentado a escrever toda uma lista doutras coisas que também não contariam como sexo conforme esse jeito de pensar, mas assuntos do meu gosto prevalecerão.
        
        
        Não se supõe que filósofos brinquem com porcos jogos de palavras advocatícias. Imagina que o X está atado sobre uma mesa especial [que se separa em duas] bloqueando o meu acesso à geladeira; e essa mesa tem, porém, uma alavanca. Caso eu trate de puxá-la, a mesa mover-se-á energizada por um motor elétrico em duas direções opostas. O X será dividido ao meio conforme a mesa se separa. O acesso ao frigorífico torna-se, então, possível. De acordo com o X, eu não sou responsável pela morte excruciante do X; eu só queria comida. Minha intenção é comer, não matar. Ipso facto, eu sou inculpável. Olha, cara, estou só a puxar uma alavanca. Se o X gritar, clamando para não o matar, responder-lhe-ei que não tenho intenção de matá-lo; só estou com fome. Agora, saias tu da minha frente. Igualmente alguém motivado por ciúmes, que mata um rival no amor, poderia dizer: “Eu não quero matar ninguém. Eu só quero a mulher para mim. Minha intenção é apenas viver uma história de amor, e não assassinar; pelo amor de Deus”. Tal raciocínio é psicótico; não racional. Tratar de alguém como um meio para um fim supostamente bom não torna as ações de alguém algo moralmente correto, pelo contrário.
        
        Então o X empilha um erro moral e um erro filosófico sobre o outro. Ele concorda que a versão da alavanca equivale moralmente à versão do bonde com o indivíduo [empurrado da ponte] apenas para argumentar que isso significa que ambas as coisas devem ser feitas. Puxa a alavanca e empurra o indivíduo para parar o bonde. Ele afirma que essa sensação visceral e repugnante de empurrar alguém para parar o veículo é irracional precisamente porque há emoções envolvidas. Puxar a alavanca com indiferença é “racional” e, por conseguinte, é racional empurrar o indivíduo solitário que — no cenário — impede o veículo de matar outras pessoas.
        
        Esse é precisamente o problema: a alavanca permite-nos suprimir a nossa relutância moral e emocional para assassinar — porque ela torna o assassinato menos tangível. O assassinato torna-se mais abstrato; a realidade da pessoa que estamos a matar é-nos menos aparente. Nós não matamos seres humanos precisamente porque eles são agentes pensantes e sentimentais como nós. Se eles fossem um robô sem sentimentos, acharíamos mais fácil matá-los, e, de fato, seria menos imoral fazê-lo. Ao agirmos como um robô insensível, ironicamente também tratamos a vítima assassinada tal qual um robô sem sentimentos. Se pedirdes que alguém resolva um simples problema matemático, antes de pedir que doe para caridade, ele doará menos. A ativação de vias neurais interfere na avaliação moral e nas preferências.[4]
        
        “Os estudos a respeito de tomada de decisão em pacientes neurológicos que não conseguem processar informação emocional normalmente sugerem que: as pessoas fazem julgamentos não apenas avaliando as consequências e sua probabilidade de ocorrer, mas também e principalmente, às vezes, num nível emocional ou visceral. As lesões do setor ventromedial (que inclui o orbitofrontal) do córtex pré-frontal interferem no processamento normal de sinais emocionais ou “somáticos”, enquanto poupam a maioria das funções cognitivas básicas. Tais danos levam a prejuízos no processo de tomada de decisão que comprometem seriamente a qualidade das escolhas na vida cotidiana.” [2][5]
        
        Em meu artigo Monsters of Duty: Cordwainer Smith’s attack on Kantian morality and the suppression of feeling in Scanners Live in Vain — donde provém a passagem sobremencionada — argumento que o conto de Cordwainer Smith é uma análise brilhante do papel que a emoção tem na tomada de decisão moral. A moralidade não pode ser derivada meramente de processos racionais. No centro da moralidade está a recognição de que a vida humana é sagrada porque somos feitos à imagem de Deus[6]. Sem este apelo ao valor intrínseco, derivado duma fonte divina, a moralidade não pode funcionar. O valor extrínseco é parasita do valor intrínseco. A reciprocidade, que consiste fundamentalmente em trocar presentes, é correta e justa. Isso é um axioma. Como todos os axiomas, a sua verdade pode ser percebida mas não provada, racionalmente ou doutro jeito, conforme o axioma P = P. Gödel provou que mesmo a matemática não consegue estar completamente formalizada e reduzida à manipulação de símbolos; insight e intuição são necessários até para isso. O hemisfério direito dá material para ser analisado; o esquerdo o analisa. Sem a entrada do Hemisfério Direito, o Hemisfério Esquerdo não tem nada por contemplar.
        
        A metaética é perfeitamente razoável; ela olha para as fundações religiosas da ética e descobre as implicações [morais]. Teorias morais, por outro lado, são assuntos do Hemisfério Esquerdo. O utilitarismo e a deontologia de Kant são tentativas de pôr as razões morais num fundamento mais racional. No processo, geraram abominações morais e encorajaram pessoas a se comportar pior do que fariam se meramente seguissem as suas intuições morais; assumindo [é claro] que as pessoas não sejam imbecis morais. Ambas as teorias representam uma regressão ao bode expiatório pré-cristão: o utilitarismo diz que tudo o que for melhor para a maioria é moralmente bom — logo, ele fica ao lado da multidão versus a vítima; o kantianismo sacrifica a vítima em nome da lei moral, recusando-se até mesmo em mentir para salvar a vida de alguém — demonstrando maior fidelidade à lei moral “racional” do que à pessoa.[7] Kant está apaixonado pelo céu estrelado acima dele e a lei moral dentro de si; não pela vítima inocente. Mera racionalidade não é racional; basta dela. A tomada de decisão moral é dependente do transcendente e da pessoa que pensa e sente.
        
        Deixando o melhor para o final… Talvez me tenha ocorrido há alguns dias, durante a aula, que seria moralmente justificável atirar em quem fizesse um movimento para puxar a alavanca. Os policiais, que têm um especial dever moral, tendo jurado cumprir a lei, seriam moralmente obrigados a atirar no suposto assassino para salvar da morte uma pessoa inocente. Um civil qualquer não pode ser obrigado legalmente a prevenir crimes, mas seria moralmente louvável caso ele matasse, em defesa dos inocentes, o pretenso puxador de alavancas. Assim que fizeres um movimento para assassinar alguém, perdes teu direito à vida caso matar-te seja necessário para te parar. O X apresentou um cenário onde o suposto assassino é um insano (que tem a sua agência moral prejudicada), logo, argumenta que não há problema em matar um inocente jogando-o nos trilhos do bonde. Poder-se-ia também imaginar que alguém foi infectado com raiva, [doença] que muda o cérebro da pessoa raivosa e fá-la morder gente de forma irracional e violenta, infectando-as com uma doença que tem, efetivamente, uma taxa de letalidade de 100% — se imaginarmos que o infectado não seria capaz de chegar a um hospital em tempo de receber tratamento preventivo. Em ambos os casos, do insano e da pessoa raivosa (que também é insana), eles perderam a agência e não são mais moralmente responsáveis por suas ações. Ainda seria necessário matá-los para proteger o inocente que estivessem prestes a matar. Nenhuma pessoa seria moralmente censurável por ser privada da agência. Ambos teriam de ser mortos à maneira dum cão com raiva. Eles perderam sua humanidade na medida em que não são mais um agente moral. Eles merecem piedade, mas por ora são uma ameaça iminente para um inocente que deve ser protegido. Nenhuma dessas considerações se estende ao puxador de alavancas que intenta assassinar.`,
        imgUrl: "https://miro.medium.com/v2/resize:fit:828/format:webp/1*fqIi-75p3ZygaPZJee1v2Q.jpeg",
        date: "26 de janeiro de 2023"
    }, 
    {
        title: "Esboço de um guia de leitura para as obras de Eric Voegelin",
        content: "O acontecimento da busca é um processo histórico. O mundo de símbolos que compactamente simbolizam a realidade em qualquer ponto histórico dado tem de submeter-se à pressão da análise noética",
        imgUrl: "https://miro.medium.com/v2/resize:fit:828/format:webp/1*FWJfxePbvlv7LpIXBRV01g.jpeg",
        date: "26 de janeiro de 2023"
    }
]


export async function GET(_: unknown, contex: any){
    const post = contex.params.post
    if(post === "all") {
        return NextResponse.json(data)
    }
    if(post < data.length) {
        return NextResponse.json(data[post])
    } else {
        return NextResponse.json([])
    }
}