import Navbar from '@/components/layout/Navbar'
import './globals.css'

export const metadata = {
  title: 'Helkein Filosofadas',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="business">
      <body className='flex flex-col relative'>
        <Navbar />
        {children}
        </body>
    </html>
  )
}
